# Created by newuser for 5.9
#
xrandr --output DisplayPort-1 --mode 2560x1440 --rate 165 
#xrandr --dpi 144 
#xrandr --output DisplayPort-1 --scale 1.5x1.5 &
# export GDK_SCALE=2
# export GDK_DPI_SCALE=0.5
# export QT_SCALE_FACTOR=2
# export QT_AUTO_SCREEN_SCALE_FACTOR=1



export EDITOR=nvim
export VISUAL=nvim

#输入法环境变量
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
#export SDL_IM_MODULE=fcitx
#export GLFW_IM_MODULE=ibus

#使用bat作为man颜色输出
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"

#字体缩放环境变量
   #export QT_FONT_DPI=144
   #export QT_AUTO_SCREEN_SCALE_FACTOR=1.2
   #export QT_AUTO_SCREEN_SCALE_FACTOR=1.2
#export GDK_DPI_SCALE=1.2
#export QT_SCALE_FACTOR=1.2

#QT主题
export QT_QPA_PLATFORMTHEME=gtk2
# export QT_QPA_PLATFORMTHEME=qt5ct
export QT_QPA_PLATFORMTHEME=qt6ct
# export QT_QPA_PLATFORMTHEME=qt5ct:qt6ct
# export QT_STYLE_OVERRIDE=kvantum
   #export XDG_CURRENT_DESKTOP=GNOME

#zsh的omz配置
source ~/workspace/git/omz/omz.zsh  
export _OMZ_APPLY_PREEXEC_HOOK=true
export _OMZ_APPLY_CHPWD_HOOK=true


alias vi='nvim'

#登陆自启动X
#[ -z $DISPLAY ] && [ $(tty) = "/dev/tty1" ] && /usr/bin/qtile start -b wayland
[ -z $DISPLAY ] && [ $(tty) = "/dev/tty1" ] && startx


